# Generated by Django 3.0.3 on 2020-07-12 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Treas', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
